"""empty message

Revision ID: 8ce31fc8f5da
Revises: 
Create Date: 2022-06-24 13:08:39.180050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ce31fc8f5da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hosts_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('info', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hosts_info')
    # ### end Alembic commands ###
